INSERT INTO products(stock,name,price,description,category,image_url) VALUES
(40,'LENEVO',56785,'A reliable Lenovo laptop designed for multitasking and productivity. Powered with 12GB RAM and 256GB ROM, it ensures smooth performance for students, professionals, and everyday users. Ideal for office tools, browsing, entertainment, and light creative tasks. Long-lasting battery and durable build make it a dependable daily companion.','Laptop','https://m.media-amazon.com/images/I/71xHNSCyRsL._AC_UY218_.jpg'),
(60,'LENEVO',36785,'A compact and efficient Lenovo model featuring 8GB RAM and 256GB ROM, perfect for day‑to‑day computing. Suitable for office work, online meetings, streaming, and academic use. Offers balanced performance with good heat management, making it ideal for users who need portability and reliability at an affordable cost.','Laptop','https://m.media-amazon.com/images/I/516btukUorL._AC_UY218_.jpg'),
(36,'LENEVO',76785,'A high‑performance Lenovo laptop equipped with 16GB RAM and 512GB ROM, delivering smooth speed for programming, creative applications, light editing, and multitasking. Designed for professionals who require faster load times and efficient workflow. Sleek design, improved thermals, and strong build quality for long‑term use.','Laptop','https://m.media-amazon.com/images/I/71K-77wHn2L._AC_UY218_.jpg'),
(678,'DELL',56785,'A versatile Dell laptop offering 12GB RAM and 256GB ROM, suitable for productivity, content consumption, and work‑from‑home tasks. Known for Dell’s sturdy design, reliable performance, and comfortable keyboard experience. Great for students and professionals who need dependable speed throughout the day.','Laptop','https://m.media-amazon.com/images/I/7156bBh8W2L._AC_UY218_.jpg'),+
(87,'DELL',46785,'This Dell model features 8GB RAM and 256GB ROM, providing solid performance for everyday users. Best suited for browsing, documents, light entertainment, and office usage. Built with Dell’s signature durability, smooth display quality, and long battery backup for all‑day usage.','Laptop','https://m.media-amazon.com/images/I/81ImBTVkbmL._AC_UY218_.jpg'),
(345,'HP',67985,'A powerful HP laptop with 12GB RAM and 512GB ROM, engineered for users who need speed and ample storage. Perfect for developers, designers, analysts, and multitaskers. It offers a refined design, good battery life, and smooth system responsiveness, making it excellent for both work and entertainment.','Laptop','https://m.media-amazon.com/images/I/71+gQ9gOTuL._AC_UY218_.jpg'),
(45,'RedMi',36000,'A budget‑friendly yet capable Redmi smartphone offering 12GB RAM and 256GB ROM. Ideal for gaming, streaming, social media, and daily communication. Features a vibrant display, long battery life, and optimized software for smooth everyday usage. A great value pick for performance‑oriented users.','Mobile','https://m.media-amazon.com/images/I/81dblfYZOYL._AC_UL320_.jpg'),
(34,'RealMe C35',16000,'A stylish and lightweight RealMe C35 phone with 8GB RAM and 128GB ROM. Perfect for casual users who need reliable performance for calls, apps, browsing, and entertainment. Offers a bright display, decent camera quality, and efficient battery management for all‑day use.','Mobile','https://m.media-amazon.com/images/I/71O5RK8qS3L._AC_UL320_.jpg'),
(56,'RealMe 15R',28000,'The RealMe 15R delivers balanced performance with 12GB RAM and 128GB ROM, making it excellent for gaming, multitasking, and media use. Stylish design, fast charging, and smooth system interaction make it a solid choice for users wanting strong performance at a reasonable price.','Mobile','https://m.media-amazon.com/images/I/71+nUkNc2rL._AC_UL320_.jpg'),
(67,'Samsung',31000,'A feature‑rich Samsung smartphone with 12GB RAM and 256GB ROM, offering a premium display, smooth UI, strong cameras, and all‑day battery backup. Excellent for gaming, streaming, office apps, and photography. Ideal for users who prefer dependable, polished performance.','Mobile','https://m.media-amazon.com/images/I/71EeBkydf9L._AC_UL320_.jpg'),
(78,'Apple 17',86000,'A premium Apple device equipped with 12GB RAM and 256GB ROM, providing a seamless and fast iOS experience. Known for its smooth performance, stunning display, advanced camera system, and strong battery efficiency. Ideal for professionals and users who want top‑tier quality.','Mobile','https://m.media-amazon.com/images/I/71JGCn1z1TL._AC_UY218_.jpg'),
(34,'Apple 15 Pro',65000,'The Apple 15 Pro offers elegance and top‑notch performance with 12GB RAM and 256GB ROM. Delivers a premium camera setup, fluid display, excellent security, and a long lifespan. Perfect for creatives, business users, and anyone seeking a luxury mobile experience.','Mobile','https://m.media-amazon.com/images/I/616-Eh2FbPL._AC_UY218_.jpg'),
(45,'OnePlus Nord CE-5',26000,'A smooth and responsive OnePlus device featuring 12GB RAM and 256GB ROM. Built for performance‑focused users who enjoy gaming, multitasking, and fast charging. OxygenOS delivers a clean and fast experience, making it a reliable daily driver.','Mobile','https://m.media-amazon.com/images/I/61IOa9IrlaL._AC_UL320_.jpg'),
(56,'OnePlus',56785,'A high‑performing OnePlus phone with 12GB RAM and 512GB ROM designed for power users. Great for heavy gaming, productivity, and multimedia consumption. Features a vibrant display, rapid charging, and smooth UI for an enhanced user experience.','Mobile','https://m.media-amazon.com/images/I/61cNdwti0QL._AC_UL320_.jpg'),
(90,'Realme Buds Air 6',899,'Wireless earbuds offering ANC, powerful bass, and clear audio. Designed for music lovers and commuters who need noise reduction and long battery life. Lightweight, comfortable, and supports fast charging for on‑the‑go convenience.','Buds','https://m.media-amazon.com/images/I/613G2wUZRSL._AC_SY300_SX300_QL70_FMwebp_.jpg'),
(120,'Samsung Galaxy Buds',699,'Premium Samsung earbuds delivering crisp sound, strong bass, and comfortable fit. Great for workouts, calls, travel, and daily listening. Features seamless device connectivity, low‑latency audio, and reliable battery performance.','Buds','https://m.media-amazon.com/images/I/61Mv3cWzZeL._AC_SY300_SX300_QL70_FMwebp_.jpg'),
(21,'One plus Noice Free',999,'Wireless earbuds offering ANC, powerful bass, and clear audio. Designed for music lovers and commuters who need noise reduction and long battery life. Lightweight, comfortable, and supports fast charging for on‑the‑go convenience.','Buds','https://m.media-amazon.com/images/I/51RaySTbIVL._AC_UY218_.jpg'),
(12,'Apple AirPods',29999,'Premium Apple earbuds delivering crisp sound, strong bass, and comfortable fit. Great for workouts, calls, travel, and daily listening. Features seamless device connectivity, low‑latency audio, and reliable battery performance.','Buds','https://m.media-amazon.com/images/I/618kmr6+uoL._AC_SY300_SX300_QL70_FMwebp_.jpg');